"""Migration integrity.

Motivated by a real failure: two columns were added to `User`, `create_all()`
silently skipped them because the `users` table already existed, and the app
booted fine then 500'd on `column users.native_language does not exist`.

The guard that matters is `test_no_model_drift` — it runs Alembic's autogenerate
comparison against the live database and fails if the models and the schema have
diverged. Had it existed, it would have caught that change before the request did.

These tests need Postgres (pgvector types don't compile on SQLite), so they skip
cleanly when it isn't reachable rather than failing a hermetic CI run.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from sqlalchemy import create_engine, text

from app.core.config import settings

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = ROOT / "migrations"


def _sync_url() -> str:
    """Alembic's comparison API is synchronous — swap the asyncpg driver out."""
    return settings.DATABASE_URL.replace("+asyncpg", "+psycopg2").replace(
        "postgresql+psycopg2", "postgresql"
    )


def _db_reachable() -> bool:
    try:
        eng = create_engine(_sync_url(), pool_pre_ping=True)
        with eng.connect() as conn:
            conn.execute(text("SELECT 1"))
        eng.dispose()
        return True
    except Exception:
        return False


needs_db = pytest.mark.skipif(
    not _db_reachable(), reason="Postgres not reachable; migration checks need a real DB"
)


# ── Structure (no DB required) ────────────────────────────────────────────────


def test_alembic_is_configured() -> None:
    assert (ROOT / "alembic.ini").exists()
    assert (MIGRATIONS / "env.py").exists()


def test_at_least_one_migration_exists() -> None:
    revisions = list((MIGRATIONS / "versions").glob("*.py"))
    assert revisions, "no migrations — schema changes would be unrepeatable"


def test_alembic_ini_carries_no_credentials() -> None:
    """The URL comes from settings; a password in a checked-in ini is a leak."""
    ini = (ROOT / "alembic.ini").read_text()
    for line in ini.splitlines():
        if line.strip().startswith("sqlalchemy.url"):
            value = line.split("=", 1)[1].strip()
            assert value == "", f"alembic.ini must not hardcode a URL, found: {value!r}"


def test_migrations_import_pgvector() -> None:
    """`chunks.embedding` renders as `pgvector.sqlalchemy...` but autogenerate does
    not emit the import, so the migration dies with NameError without it."""
    for rev in (MIGRATIONS / "versions").glob("*.py"):
        source = rev.read_text()
        if "pgvector" in source and "vector.VECTOR" in source:
            assert "import pgvector" in source, f"{rev.name} uses pgvector without importing it"


def test_the_script_template_imports_pgvector() -> None:
    """So the next autogenerated migration doesn't need the same manual fix."""
    assert "import pgvector" in (MIGRATIONS / "script.py.mako").read_text()


def test_env_commits_explicitly() -> None:
    """The CREATE EXTENSION opens a transaction, which makes Alembic skip its own
    commit — `upgrade head` then reports success and applies nothing."""
    assert "connection.commit()" in (MIGRATIONS / "env.py").read_text()


def test_bootstrap_no_longer_uses_create_all() -> None:
    """create_all never ALTERs an existing table — the original bug.

    Parsed with `ast` rather than grepped: the docstring in `bootstrap.py`
    deliberately *mentions* `Base.metadata.create_all` to explain why it was
    removed, and a substring check happily matched that prose.
    """
    import ast

    source = (ROOT / "app" / "services" / "bootstrap.py").read_text()
    tree = ast.parse(source)

    attribute_chains = [
        ".".join(reversed(parts))
        for node in ast.walk(tree)
        if isinstance(node, ast.Attribute)
        for parts in [_attr_chain(node)]
        if parts
    ]
    assert not any(c.endswith("metadata.create_all") for c in attribute_chains), (
        "bootstrap still calls create_all, which silently skips ALTERs on existing tables"
    )
    assert any(c.endswith("command.upgrade") for c in attribute_chains), (
        "bootstrap should run `alembic upgrade head`"
    )


def _attr_chain(node) -> list[str]:
    """Flatten `a.b.c` into ['c', 'b', 'a']; [] if it isn't a plain attribute chain."""
    import ast

    parts: list[str] = []
    cur = node
    while isinstance(cur, ast.Attribute):
        parts.append(cur.attr)
        cur = cur.value
    if isinstance(cur, ast.Name):
        parts.append(cur.id)
        return parts
    return []


# ── Live database ─────────────────────────────────────────────────────────────


@needs_db
def test_database_is_stamped() -> None:
    """An unstamped DB means migrations were never applied to it."""
    eng = create_engine(_sync_url())
    with eng.connect() as conn:
        row = conn.execute(text("SELECT version_num FROM alembic_version")).first()
    eng.dispose()
    assert row is not None and row[0], "database has no alembic revision"


@needs_db
def test_no_model_drift() -> None:
    """THE guard: models and live schema must agree.

    This is what would have caught `native_language`/`target_language` never
    reaching the database.
    """
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    from app.db.models import Base

    eng = create_engine(_sync_url())
    try:
        with eng.connect() as conn:
            ctx = MigrationContext.configure(
                conn,
                opts={
                    "compare_type": True,
                    "compare_server_default": True,
                    "include_object": lambda o, name, t, r, c: not (
                        t == "table" and name == "alembic_version"
                    ),
                },
            )
            diff = compare_metadata(ctx, Base.metadata)
    finally:
        eng.dispose()

    assert not diff, (
        "models and database schema have diverged — run:\n"
        "  alembic revision --autogenerate -m 'describe the change'\n"
        "  alembic upgrade head\n"
        f"pending changes: {diff}"
    )
