"""prompt overrides

Revision ID: 7fb9b3f36155
Revises: 846f6be9f412
Create Date: 2026-08-03 22:48:42.387282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# `chunks.embedding` is a pgvector column; autogenerate references
# `pgvector.sqlalchemy...` without importing it, so it is imported here for
# every migration rather than being re-fixed by hand each time.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7fb9b3f36155'
down_revision: Union[str, Sequence[str], None] = '846f6be9f412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_overrides_key'), 'prompt_overrides', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_overrides_key'), table_name='prompt_overrides')
    op.drop_table('prompt_overrides')
    # ### end Alembic commands ###
