"""email verification and oauth provider

Revision ID: 846f6be9f412
Revises: b1c4a7e90f11
Create Date: 2026-08-03 21:22:43.766234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# `chunks.embedding` is a pgvector column; autogenerate references
# `pgvector.sqlalchemy...` without importing it, so it is imported here for
# every migration rather than being re-fixed by hand each time.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '846f6be9f412'
down_revision: Union[str, Sequence[str], None] = 'b1c4a7e90f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='password', nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verify_token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('verify_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_verify_token_hash'), 'users', ['verify_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verify_token_hash'), table_name='users')
    op.drop_column('users', 'verify_token_expires')
    op.drop_column('users', 'verify_token_hash')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
