"""document content kind

Revision ID: b11b5a4db993
Revises: 34cc60963644
Create Date: 2026-08-04 12:33:30.385278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# `chunks.embedding` is a pgvector column; autogenerate references
# `pgvector.sqlalchemy...` without importing it, so it is imported here for
# every migration rather than being re-fixed by hand each time.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b11b5a4db993'
down_revision: Union[str, Sequence[str], None] = '34cc60963644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_kind', sa.String(length=16), server_default='prose', nullable=False))
    op.create_index(op.f('ix_documents_content_kind'), 'documents', ['content_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_kind'), table_name='documents')
    op.drop_column('documents', 'content_kind')
    # ### end Alembic commands ###
