"""describe the change

Revision ID: d32bc8b1076a
Revises: dad9a12cb85a
Create Date: 2026-07-31 07:02:09.863146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# `chunks.embedding` is a pgvector column; autogenerate references
# `pgvector.sqlalchemy...` without importing it, so it is imported here for
# every migration rather than being re-fixed by hand each time.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd32bc8b1076a'
down_revision: Union[str, Sequence[str], None] = 'dad9a12cb85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
